import { useState } from "react";
import { Link } from "react-router-dom";
import { getToken } from "../utils/authStore";
import { useAuth } from "../components/AuthContext";

function Settings() {
  const { user, setUser, signOut } = useAuth();
  const [name, setName] = useState(user.name); const [currentPassword, setCurrentPassword] = useState(""); const [newPassword, setNewPassword] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function request(path, options) { const response = await fetch(`/api${path}`, { ...options, headers: { "Content-Type": "application/json", Authorization: `Bearer ${getToken()}`, ...(options?.headers || {}) } }); const data = await response.json(); if (!response.ok) throw new Error(data.message || "Unable to update settings"); return data; }
  async function saveProfile(event) { event.preventDefault(); setError(""); setMessage(""); try { const data = await request("/auth/profile", { method: "PATCH", body: JSON.stringify({ name }) }); setUser(data.user); setMessage("Profile updated successfully."); } catch (err) { setError(err.message); } }
  async function savePassword(event) { event.preventDefault(); setError(""); setMessage(""); try { await request("/auth/password", { method: "POST", body: JSON.stringify({ currentPassword, newPassword }) }); setCurrentPassword(""); setNewPassword(""); setMessage("Password updated successfully."); } catch (err) { setError(err.message); } }
  return <div className="page-wrap settings-page"><header className="page-header"><div><span className="eyebrow">ACCOUNT / SETTINGS</span><h1>Account settings</h1><p>Manage your profile, security, and service desk preferences.</p></div><Link className="back-link" to="/">← Back to overview</Link></header>{(message || error) && <div className={error ? "form-error" : "settings-success"}>{error || message}</div>}<div className="settings-grid"><section className="panel"><div className="panel-heading"><div><span className="eyebrow">PROFILE</span><h2>Personal information</h2></div></div><form className="settings-form" onSubmit={saveProfile}><label>Full name<input value={name} onChange={(event) => setName(event.target.value)} required /></label><label>Email address<input value={user.email} disabled /></label><button className="button primary" type="submit">Save changes</button></form></section><section className="panel"><div className="panel-heading"><div><span className="eyebrow">SECURITY</span><h2>Change password</h2></div></div><form className="settings-form" onSubmit={savePassword}><label>Current password<input type="password" value={currentPassword} onChange={(event) => setCurrentPassword(event.target.value)} required /></label><label>New password <small className="field-hint">8 characters minimum</small><input type="password" minLength="8" value={newPassword} onChange={(event) => setNewPassword(event.target.value)} required /></label><button className="button secondary" type="submit">Update password</button></form></section><section className="panel settings-wide"><div className="panel-heading"><div><span className="eyebrow">SESSION INFORMATION</span><h2>Account activity</h2></div></div><div className="session-grid"><div><span>Signed-in email</span><strong>{user.email}</strong></div><div><span>Access level</span><strong>{user.role === "admin" ? "Administrator" : "Standard user"}</strong></div><div><span>Last login</span><strong>{user.lastLoginAt ? new Date(user.lastLoginAt).toLocaleString() : "Not available"}</strong></div></div></section><section className="panel settings-wide danger-panel"><div><span className="eyebrow">SESSION CONTROL</span><h2>Sign out</h2><p>End your current session on this device.</p></div><button className="button danger" onClick={signOut}>Sign out</button></section></div></div>;
}

export default Settings;
